sudo: required
language: python

python:
  - "3.6"
services:
  - docker
env:
  - PYTHONUNBUFFERED=TRUE

if: branch = master OR type = pull_request

install:
  - pip install pipsi
  - pipsi install .

script:
  - echo "The test passes"

deploy:
  provider: script
  skip_cleanup: true
  on: { branch: master }
  script:
    - travis_wait 30 lambdipy release
